export {
	createTextAnnotation,
	createFigureAnnotation,
	createBlurAnnotation,
	createFreehandAnnotation,
	createImageAnnotation,
	moveAnnotation,
	resizeAnnotation,
	retimeAnnotation,
	updateAnnotationStyle,
	updateAnnotationText,
	setAnnotationZIndex,
	addFadeInEffect,
	addFadeOutEffect,
	addFadeInOutEffect,
	getActiveAnnotations,
	bringToFront,
	sendToBack,
	duplicateAnnotation,
} from "./AnnotationEngine.js";
